/** HTTP 상태별 API 에러 코드 (SSOT: 백엔드 에러 코드 표). */
export const API_ERROR_CODES_BY_STATUS = {
  400: ['VALIDATION_ERROR', 'INVALID_CURSOR', 'INVALID_PARENT_COMMENT', 'INVALID_IMAGE_EXTENSION', 'OAUTH_ACCOUNT'],
  401: ['TOKEN_INVALID', 'INVALID_CREDENTIALS', 'TOKEN_EXPIRED', 'TOKEN_REUSE', 'OAUTH_FAILED'],
  403: ['FORBIDDEN', 'TEAM_MISMATCH'],
  404: ['NOT_FOUND'],
  409: ['DUPLICATE_EMAIL', 'DUPLICATE_ENTRY'],
  500: ['INTERNAL_ERROR'],
} as const;

/** API 에러 코드 문자열 유니온. */
export type ApiErrorCode = (typeof API_ERROR_CODES_BY_STATUS)[keyof typeof API_ERROR_CODES_BY_STATUS][number];
