import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Toast from '@/src/components/common/toast/Toast';
import Providers from './providers';
import Sidebar from '@/src/components/common/sidebar/Sidebar';
import Topbar from '@/src/components/common/sidebar/Topbar';

const pretendard = localFont({
  src: './fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.className} h-full antialiased`}>
      <body className="flex min-h-full bg-slate-100">
        <Providers>
          <Toast />
          <Topbar />
          <Sidebar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
