import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Toast from '@/src/components/common/toast/Toast';
import Providers from './providers';
import { NextIntlClientProvider } from 'next-intl';
import { isValidLocale } from '@/src/i18n/routing';
import { notFound } from 'next/navigation';

const pretendard = localFont({
  src: '../fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  // 유효하지 않은 locale이면 404
  if (!isValidLocale(locale)) {
    notFound();
  }

  return (
    <html lang={locale} className={`${pretendard.className} h-full antialiased`}>
      <body className="flex min-h-full bg-slate-100">
        <NextIntlClientProvider>
          <Providers>
            <Toast />
            {children}
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
